//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EStore.DL.Mapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductSingle
    {
        public long Id { get; set; }
        public Nullable<decimal> BuyPrice { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<long> IsNew { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<long> OrderId { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<long> SupplierInvoicePositionId { get; set; }
        public Nullable<long> SupplierInvoiceId { get; set; }
        public string Notes { get; set; }
    
        public virtual tblOrder tblOrder { get; set; }
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblSupplierInvoice tblSupplierInvoice { get; set; }
        public virtual tblSupplierInvoicePosition tblSupplierInvoicePosition { get; set; }
    }
}
