//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EStore.DL.Mapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.tblFiles = new HashSet<tblFile>();
            this.tblProductFeedbacks = new HashSet<tblProductFeedback>();
            this.tblProductSingles = new HashSet<tblProductSingle>();
            this.tblSupplierInvoicePositions = new HashSet<tblSupplierInvoicePosition>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Descripton { get; set; }
        public Nullable<long> ManufacterId { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public string Specs { get; set; }
        public string YandexUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFile> tblFiles { get; set; }
        public virtual tblManufacter tblManufacter { get; set; }
        public virtual tblProductCategory tblProductCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductFeedback> tblProductFeedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductSingle> tblProductSingles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSupplierInvoicePosition> tblSupplierInvoicePositions { get; set; }
    }
}
